application: sandbox550
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /oauth2callback
  script: oauth2client.appengine.application

- url: .*
  script: main.application

