application: sandbox550
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: controllers.main.app

libraries:
- name: PIL
  version: "1.1.7"
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
